version: '3.8'
services:
  
  db:
    container_name: todo_db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=todo_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
    ports:
      - 3306:3306 # Điều chỉnh cổng tùy ý
    

  backend:
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
# docker compose -p todolist-finnal up -d
